version: 2
jobs:
  build:
    docker:
      - image: iganarix/base-alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "62:6d:f6:0d:7d:39:54:b0:b7:d5:0e:ef:43:05:e6:f5"
      - run:
          name: check OS
          command: "uname -a"
      - run:
          name: install curl
          command: "apt-get install -y curl"
      - run:
          name: remote update
          command: "git remote update -p"
      - run:
          name: setting git config
          command: "curl 'https://gist.githubusercontent.com/iganari/9d1fb09acaf471c039c5d85b8ecb3423/raw/58c1bc8b76fe9fb814d0995c89b30530dad75bc4/setting-git-iganari' | sh"
      - run:
          name: checkout branch to readme-only
          command: "git checkout modify-readme-only"
      - run:
          name: pull ${CIRCLE_BRANCH} branch
          command: "git pull origin ${CIRCLE_BRANCH}"
      - run:
          name: push readme-only branch
          command: "git push origin modify-readme-only"

workflows:
  version: 2
  build_only:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
                - feature/modify-by-python
                - feature/chk-list-blank
